# Generated by Django 3.1.7 on 2021-03-31 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_article_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('c_code', models.CharField(default='PY-2011', max_length=20, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=1, verbose_name='duration')),
                ('begin_date', models.DateField(default=datetime.date(2021, 3, 31))),
                ('c_num', models.ManyToManyField(to='myapp.Student')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
    ]
